title: Startpage Emporium
description: >
    A curated showcase of startpages for your browser by 0XE4. Currently listing over 70 beautiful startpages.
baseurl: ""

# Build settings
exclude: ["README.md"]
permalink: pretty
gems:
  - jekyll-sitemap
